#
#  Copyright 2024 The GUAC Authors.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

openapi: "3.0.0"
paths:
  # the query endpoints are for simple queries of the graph
  # the analysis endpoints are for more advanced questions
  "/healthz":
    get:
      summary: Health check the server
      operationId: healthCheck
      responses:
        "200":
          description: Indicates the server is healthy
          content:
            application/json:
              schema:
                type: string
  "/query/dependencies":
    get:
      summary: Retrieve the dependencies of a package
      operationId: retrieveDependencies
      parameters:
        - $ref: "#/components/parameters/PaginationSpec"
        - name: purl
          description: the purl of the dependent package
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/PurlList"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "502":
          $ref: "#/components/responses/BadGateway"
  "/analysis/dependencies":
    get:
      summary: Identify the most important dependencies
      operationId: analyzeDependencies
      parameters:
        - $ref: "#/components/parameters/PaginationSpec"
        - name: sort
          description: >
            The sort order of the packages
              * 'frequency' - The packages with the highest number of dependents
              * 'scorecard' - The packages with the lowest OpenSSF scorecard score
          in: query
          required: true
          schema:
            type: string
            enum:
              - frequency
              - scorecard
      responses:
        "200":
          $ref: "#/components/responses/PurlList"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "502":
          $ref: "#/components/responses/BadGateway"
  "/query/pkgInfo/{purl}":
   get:
     summary: Get all information related to the package based on the purl
     operationId: getPackageInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: purl
         description: the purl of the query package
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/Info"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/pkgInfo/{purl}/vulns":
   get:
     summary: Get vulnerability information related to the package based on the purl
     operationId: getPackageVulnInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: purl
         description: the purl of the query package
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/VulnInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/pkgInfo/{purl}/sbom":
   get:
     summary: Get sbom location related to the package based on the purl
     operationId: getPackageSbomInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: purl
         description: the purl of the query package
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/SbomInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/pkgInfo/{purl}/slsa":
   get:
     summary: Get slsa location related to the package based on the purl
     operationId: getPackageSlsaInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: purl
         description: the purl of the query package
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/SlsaInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/artInfo/{hash}":
   get:
     summary: Get all information related to the artifact based on the hash
     operationId: getArtifactInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: hash
         description: the hash of the artifact
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/Info"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/artInfo/{hash}/vulns":
   get:
     summary: Get vulnerability information related to the artifact based on the hash
     operationId: getArtifactVulnInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: hash
         description: the hash of the artifact
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/VulnInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/artInfo/{hash}/sbom":
   get:
     summary: Get sbom location related to the artifact based on the hash
     operationId: getArtifactSbomInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: hash
         description: the hash of the artifact
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/SbomInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
  "/query/artInfo/{hash}/slsa":
   get:
     summary: Get slsa location related to the artifact based on the hash
     operationId: getArtifactSlsaInformation
     parameters:
       - $ref: "#/components/parameters/PaginationSpec"
       - name: hash
         description: the hash of the artifact
         in: path
         required: true
         schema:
           type: string
     responses:
       "200":
         $ref: "#/components/responses/SlsaInfo"
       "400":
         $ref: "#/components/responses/BadRequest"
       "500":
         $ref: "#/components/responses/InternalServerError"
       "502":
         $ref: "#/components/responses/BadGateway"
components:
  parameters:
    PaginationSpec:
      name: PaginationSpec 
      in: query
      description: >
        The pagination configuration for the query.
          * 'PageSize' specifies the number of results returned
          * 'Cursor' is returned by previous calls and specifies what page to return
      required: false
      schema:
        type: object
        properties:
          PageSize: 
            type: integer 
          Cursor: 
            type: string
  schemas:
    Purl:
      type: string
    Vulnerability:
      type: string
    CertifyBad:
      type: string
    Slsa:
      type: string
    Sbom:
      type: string
    PaginationInfo:
      type: object
      description: >
        Contains the cursor to retrieve more pages. If there are no more, 
        NextCursor will be nil.
      properties: 
        NextCursor:
          type: string
        TotalCount:
          type: integer
    Error:
      type: object
      required:
        - Message
      properties:
        Message:
          type: string
  responses:
    # for code 200
    Info:
      description: bulk information
      content:
        application/json:
          schema:
            type: object
            required: 
              - PaginationInfo
              - certifyBads
              - vulnerabilities
              - SbomList
              - SlsaList
            properties:
              PaginationInfo:
                $ref: "#/components/schemas/PaginationInfo"
              vulnerabilities:
                type: array
                items: 
                  $ref: "#/components/schemas/Vulnerability"
              certifyBads:
                type: array
                items: 
                  $ref: "#/components/schemas/CertifyBad"
              SbomList:
                type: array
                items: 
                  $ref: "#/components/schemas/Sbom"
              SlsaList:
                type: array
                items: 
                  $ref: "#/components/schemas/Slsa"
    VulnInfo:
      description: purl information
      content:
        application/json:
          schema:
            type: object
            required: 
              - PaginationInfo
              - vulnerabilities
              - certifyBads

            properties:
              PaginationInfo:
                $ref: "#/components/schemas/PaginationInfo"
              vulnerabilities:
                type: array
                items: 
                  $ref: "#/components/schemas/Vulnerability"
              certifyBads:
                type: array
                items: 
                  $ref: "#/components/schemas/CertifyBad"
    SbomInfo:
      description: sbom location
      content:
        application/json:
          schema:
            type: object
            required: 
              - PaginationInfo
              - SbomList
            properties:
              PaginationInfo:
                $ref: "#/components/schemas/PaginationInfo"
              SbomList:
                type: array
                items: 
                  $ref: "#/components/schemas/Sbom"
    SlsaInfo:
      description: slsa location
      content:
        application/json:
          schema:
            type: object
            required: 
              - PaginationInfo
              - SlsaList
            properties:
              PaginationInfo:
                $ref: "#/components/schemas/PaginationInfo"
              SlsaList:
                type: array
                items: 
                  $ref: "#/components/schemas/Slsa"
    PurlList:
      description: A list of purls
      content:
        application/json:
          schema:
            type: object
            required: 
              - PaginationInfo
              - PurlList
            properties:
              PaginationInfo:
                $ref: "#/components/schemas/PaginationInfo"
              PurlList:
                type: array
                items: 
                  $ref: "#/components/schemas/Purl"
    # for code 400, client side error
    BadRequest:
      description: Bad request, such as from invalid or missing parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    # for code 500
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    # for code 502
    BadGateway:
      description: The server encountered an error connecting to the data backend
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
